### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by yaoliu0803** [clissa/fluocells-scientific-data#1]
Hi ,your work is excellent! in your paper supply the dataset link [https://amsacta.unibo.it/id/eprint/7347], but I can't open it. Can you provide valid data set links? 
If you see my question, I hope you can reply as soon as possible. Thanks again

**Comment by clissa** [comment]
Hi @yaoliu0803, I am glad you found our work valuable 🙂 
I confirm the link is correct, but it will only be accessible at acceptance of the preprint by a journal. Unfortunately, I am not sure when this will happen but I would expect it to be within one/two months (🤞🏽).
May it help using the [v1 version](http://amsacta.unibo.it/id/eprint/6706/)? It contains the yellow dataset with minor modifications.

**Comment by clissa** [comment]
@yaoliu0803 the dataset has been released at: https://amsacta.unibo.it/id/eprint/7347/ together with the paper: https://rdcu.be/dyjh7 😃
